version: '3.3'
services:
  db:
    image: postgres:15.0
    restart: unless-stopped 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  web:
    #image: bonajo/gameshow:0.0.1
    image: gameshow:dev
    restart: unless-stopped 
    user: ${UID}:${GID}
    ports:
      - '127.0.0.1:${WEB_PORT}:5000'
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./StaticFiles:/app/StaticFiles
    depends_on:
      - db